// <auto-generated />
namespace FShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_product_entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_product_entity));
        
        string IMigrationMetadata.Id
        {
            get { return "202102180355380_update_product_entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
